theme: fix issues causing JS console errors
Added missing font (fontawesome-webfont.woff2), removed
map directive causing (silent) 404 errors for missing
css.map files, and fixed a deprecated $(window).load call
that was causing an Uncaught TypeError: a.indexOf is not a function
error.

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>